### ISSUE TITLE
Question of the difference

### ISSUE THREAD

**Issue by JBlond** [bashclub/backup-zfs#1]
With only reading the code on the surface, I didn't understand the difference between [backup-zfs](https://github.com/bashclub/bashclub-zfs-push-pull/blob/master/backup-zfs) and [bashclub-zfs](https://github.com/bashclub/bashclub-zfs-push-pull/blob/master/bashclub-zfs) since they share most of the code.

**Comment by cpzengel** [comment]
extra features
you can choose from all snapshots on first sync, intermediate snapshots, alternate ssh port, SSH Compression and the process does not run twice.
So you can just keep the own Snapshots or you can decide to take the whole chain at the beginning -R and then all intermediate Autosnapshots -I etc, more to come

**Comment by JBlond** [comment]
Thanks!
