### ISSUE TITLE
fehlende Berechtigung in /root/bashclub-zfs unter Debian Bullseye

### ISSUE THREAD

**Issue by md61267** [bashclub/backup-zfs#2]
Hallo,
ich habe die neueste Version von github heruntergeladen, die 02pull angepasst und das Script bashclub-zfs in /root/ gelegt. Diese habe ich auch in der 02pull angegeben. Beim Versuch zu starten erscheint folgendes:

root@pve013:~/bashclub-zfs-push-pull# ./02pull

Repliziere von 192.168.54.17 subvol-100013-disk-0 subvol-100015-disk-0 subvol-100015-disk-2 vm-100-disk-0 vm-100011-disk-0 vm-100012-disk-0 vm-100012-disk-5 vm-100012-disk-6 vm-100014-disk-0 vm-100016-disk-0 vm-100019-disk-0 vm-100019-disk-1 vm-10012-test-221217 vm-10012-test-230111 vm-110001-disk-0 vm-110001-disk-1

./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
./02pull: Zeile 13: /root/bashclub-zfs: Keine Berechtigung
root@pve013:~/bashclub-zfs-push-pull#

**Comment by cpzengel** [comment]
chmod +x bashclub-zfs

**Comment by md61267** [comment]
thx
issue resolved
